/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/zoom-area.module';
import * as i2 from '../node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as i3 from '../node_modules/ionic-angular/components/alert/alert-component.ngfactory';
import * as i4 from '../node_modules/ionic-angular/components/app/app-root.ngfactory';
import * as i5 from '../node_modules/ionic-angular/components/loading/loading-component.ngfactory';
import * as i6 from '../node_modules/ionic-angular/components/modal/modal-component.ngfactory';
import * as i7 from '../node_modules/ionic-angular/components/picker/picker-component.ngfactory';
import * as i8 from '../node_modules/ionic-angular/components/popover/popover-component.ngfactory';
import * as i9 from '../node_modules/ionic-angular/components/select/select-popover-component.ngfactory';
import * as i10 from '../node_modules/ionic-angular/components/toast/toast-component.ngfactory';
import * as i11 from '@angular/common';
import * as i12 from '@angular/forms';
import * as i13 from '@angular/platform-browser';
import * as i14 from '@angular/animations/browser';
import * as i15 from '@angular/platform-browser/animations';
import * as i16 from '@angular/animations';
import * as i17 from 'ionic-angular/module';
export const ZoomAreaModuleNgFactory:i0.NgModuleFactory<i1.ZoomAreaModule> = i0.ɵcmf(i1.ZoomAreaModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ActionSheetCmpNgFactory,i3.AlertCmpNgFactory,i4.IonicAppNgFactory,
              i5.LoadingCmpNgFactory,i6.ModalCmpNgFactory,i7.PickerCmpNgFactory,i8.PopoverCmpNgFactory,
              i9.SelectPopoverNgFactory,i10.ToastCmpNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i11.NgLocalization,i11.NgLocaleLocalization,[i0.LOCALE_ID]),
          i0.ɵmpd(4608,i12.ɵi,i12.ɵi,([] as any[])),i0.ɵmpd(4608,i12.FormBuilder,i12.FormBuilder,
              ([] as any[])),i0.ɵmpd(4608,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(5120,
              i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,
              ([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i13.DomSanitizer,i13.ɵe,[i11.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i13.DomSanitizer]),i0.ɵmpd(4608,i13.HAMMER_GESTURE_CONFIG,
              i13.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,i13.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i13.ɵDomEventsPlugin(p0_0),new i13.ɵKeyEventsPlugin(p1_0),
                    new i13.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i11.DOCUMENT,i11.DOCUMENT,i11.DOCUMENT,i13.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i13.EventManager,i13.EventManager,[i13.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i13.ɵDomSharedStylesHost,i13.ɵDomSharedStylesHost,
              [i11.DOCUMENT]),i0.ɵmpd(4608,i13.ɵDomRendererFactory2,i13.ɵDomRendererFactory2,
              [i13.EventManager,i13.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i14.AnimationDriver,
              i15.ɵc,([] as any[])),i0.ɵmpd(5120,i14.ɵAnimationStyleNormalizer,i15.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i14.ɵAnimationEngine,i15.ɵb,[i14.AnimationDriver,
              i14.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i15.ɵe,
              [i13.ɵDomRendererFactory2,i14.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i13.ɵSharedStylesHost,(null as any),[i13.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i13.Meta,i13.Meta,
              [i11.DOCUMENT]),i0.ɵmpd(4608,i13.Title,i13.Title,[i11.DOCUMENT]),i0.ɵmpd(4608,
              i16.AnimationBuilder,i15.ɵBrowserAnimationBuilder,[i0.RendererFactory2,
                  i13.DOCUMENT]),i0.ɵmpd(512,i11.CommonModule,i11.CommonModule,([] as any[])),
          i0.ɵmpd(512,i12.ɵba,i12.ɵba,([] as any[])),i0.ɵmpd(512,i12.FormsModule,i12.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i12.ReactiveFormsModule,i12.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i17.IonicModule,i17.IonicModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i13.ɵa,([] as any[])),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any) => {
                return [i13.ɵc(p0_0,p0_1)];
              },[[2,i13.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i13.BrowserModule,i13.BrowserModule,[[3,i13.BrowserModule]]),
          i0.ɵmpd(512,i15.BrowserAnimationsModule,i15.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i1.ZoomAreaModule,i1.ZoomAreaModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RldnJlcS9yZXBvcy9pb25pYzItem9vbS1hcmVhL3NyYy96b29tLWFyZWEubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2RldnJlcS9yZXBvcy9pb25pYzItem9vbS1hcmVhL3NyYy96b29tLWFyZWEubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
